# Lab 1 - Python Lab
## Author: *your name here*
## Date: 11:59 PM February 13, 2022

You should have access to a Notebook software that can edit and run `.ipynb` files. Prefereably, I recommend using Jupyter Notebook through the [Anaconda package](https://docs.anaconda.com/anaconda/install/index.html). You will write code in places marked "TO-DO" to complete the problems. Most of this will be a pure programming assignment but there are some questions that instead ask you to "write a few sentences". This is a writing class afterall. The tools for the solutions to these probelms can be found in the class python practice lectures. I encourage you to use Google and to flex your Google-Fu skills, but you should be learning. If you copy and paste esoteric code you don't understand, you're only cheating youself.

To "hand in" this lab, you should first download this file. The best way to do this is by cloning the class repository, solving it on your local device, then copying this file into your personal class repository on Github. For the student's convenience I will upload the Python Labs and Practice Lectures onto the Slack channel. 

Work on this with your friends! Programming is often a collaborative effort.

### Basic Python Skills

1. Print out the numerical constant pi with ten digits after the decimal point using the internal constant `pi`.

In [1]:
# TO-DO
import numpy as np
round(np.pi,10)

3.1415926536

2. Sum up the first 103 terms of the series 1 + 1/2 + 1/4 + 1/8 + ...

In [2]:
# TO-DO
y = 1
for i in range(1,103):
    y += 1/i
y

6.207082429307257

3. Find the product of the first 37 terms in the sequence 1/3, 1/6, 1/9  ...

In [3]:
# TO-DO
j = 1
for i in range(3,37,3):
    j *= (1/i)
j

3.9283301416089635e-15

4. Find the product of the first 387 terms of `1 * 1/2 * 1/4 * 1/8 *` ...

In [4]:
# TO-DO
j = 1
for i in range(2,387,2):
    j *= (1/i)
j

0.0

5. Is this answer *exactly* correct? 

*write your answer here*

6. Figure out a means to express the answer more exactly. Not compute exactly, but express more exactly.

In [5]:
# TO-DO
-np.log(2)*sum(range(1,387))

-51771.856063202875

7. Create the sequence `x = [Inf, 20, 18, ..., -20]`.

In [7]:
# TO-DO
x = list(range(-20,21))
x.append(np.inf)
x.sort(reverse=True)
np.array(x)

array([ inf,  20.,  19.,  18.,  17.,  16.,  15.,  14.,  13.,  12.,  11.,
        10.,   9.,   8.,   7.,   6.,   5.,   4.,   3.,   2.,   1.,   0.,
        -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,  -9., -10., -11.,
       -12., -13., -14., -15., -16., -17., -18., -19., -20.])

8. Create the sequence `x = [log_3(Inf), log_3(100), log_3(98), ... log_3(-20)]`.

In [51]:
# TO-DO
y = np.log(x)/np.log(3)
y_ = np.copy(y)
y

/var/folders/tz/_fthv9sx6pq_hc0qzmtt7w7h0000gn/T/ipykernel_80791/2280979774.py:2: RuntimeWarning: divide by zero encountered in log
  y = np.log(x)/np.log(3)
/var/folders/tz/_fthv9sx6pq_hc0qzmtt7w7h0000gn/T/ipykernel_80791/2280979774.py:2: RuntimeWarning: invalid value encountered in log
  y = np.log(x)/np.log(3)


array([       inf, 2.72683303, 2.68014386, 2.63092975, 2.57890192,
       2.52371901, 2.46497352, 2.4021735 , 2.33471752, 2.26185951,
       2.18265834, 2.09590327, 2.        , 1.89278926, 1.77124375,
       1.63092975, 1.46497352, 1.26185951, 1.        , 0.63092975,
       0.        ,       -inf,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan])

9. Comment on the appropriateness of the non-numeric values.

NAN occurs because you cannot take the log of a negative number.
-Inf occurs when you take the log of 0.
<span style="color:red">Very appropriate, all negative values are NAN</span></br>
10. Create a vector of booleans where the entry is true if `x[i]` is positive and finite.

In [55]:
# TO-DO
for i in range(len(y)):
    if y[i] >= 0 and y[i] != np.inf:
        y[i] = True
    else:
        y[i] = False

y

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

11. Locate the indices of the non-real numbers in this vector. Hint: use the `help` function. Don't hesitate to use the documentation via `help()`.

In [56]:
# TO-DO
res1 = np.where(y == False)
res1


(array([ 0, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41]),)

12. Locate the indices of the infinite quantities in this vector. 
<span style = "color:deeppink">Asking questions in this order is bad practice the array has already been updated to a bool array </span>

In [36]:
# TO-DO
res = np.where(np.logical_or(y_ == np.inf, y_ == -np.inf))
res

(array([ 0, 21]),)

13. Locate the indices of the min and max in this vector.

In [41]:
# TO-DO
print(' min index: ',np.where(y_==min(y_))[0],'\n','max index: ',np.where(y_==max(y_))[0])

 min index:  [21] 
 max index:  [0]


14. Count the number of unique values in `x`.

In [47]:
# TO-DO
print('This accounts for +/- inf and 1 NAN: ',len(np.unique(y_)))

This accounts for +/- inf and 1 NAN:  23


15. Cast `x` to a factor. Do the number of levels make sense?

In [50]:
# TO-DO
y_.astype(int)

array([-9223372036854775808,                    2,                    2,
                          2,                    2,                    2,
                          2,                    2,                    2,
                          2,                    2,                    2,
                          2,                    1,                    1,
                          1,                    1,                    1,
                          1,                    0,                    0,
       -9223372036854775808, -9223372036854775808, -9223372036854775808,
       -9223372036854775808, -9223372036854775808, -9223372036854775808,
       -9223372036854775808, -9223372036854775808, -9223372036854775808,
       -9223372036854775808, -9223372036854775808, -9223372036854775808,
       -9223372036854775808, -9223372036854775808, -9223372036854775808,
       -9223372036854775808, -9223372036854775808, -9223372036854775808,
       -9223372036854775808, -9223372036854775808, 

16. Cast `x` to integers. What do we learn about R's infinity representation in the integer data type?

In [53]:
# TO-DO
print("we learn that python's max int value is: ",9223372036854775808)

we learn that python's max int value is:  9223372036854775808


17. Use `x` to create a new vector `y` containing only the positive real numbers in x.

In [60]:
# TO-DO
res2 = np.where(y == True)
y1 = np.take(y_,res2)
y1

array([[2.72683303, 2.68014386, 2.63092975, 2.57890192, 2.52371901,
        2.46497352, 2.4021735 , 2.33471752, 2.26185951, 2.18265834,
        2.09590327, 2.        , 1.89278926, 1.77124375, 1.63092975,
        1.46497352, 1.26185951, 1.        , 0.63092975, 0.        ]])

18. Use the left rectangle method to numerically integrate x^2 from 0 to 1 with rectangle width size 1e-6.

In [61]:
# TO-DO
delta = 1e-6
x = np.sum(np.arange(0,1,delta)**2)*delta
x

0.33333283333349994

19. Calculate the average of 100 realizations of standard Bernoullis in one line using the `random` library.

In [63]:
# TO-DO
np.mean(np.random.randint(2,size = 100))

0.5

20. Calculate the average of 500 realizations of Bernoullis with p = 0.9.

In [64]:
# TO-DO
import random
s = [0,1]
np.mean(random.choices(s, weights=(10, 90), k=500))

0.904

21. Calculate the average of 1000 realizations of Bernoullis with p = 0.9.

In [66]:
# TO-DO
s = [0,1]
np.mean(random.choices(s, weights=(10, 90), k=1000))

0.91

23. Convert this variable into three binary variables without any information loss and put them into a data matrix.

In [117]:
# TO-DO
import pandas as pd
s = [0,1,2,3]
a = np.random.choice(s, size = 100)
array = np.zeros([100,4])
for j in range(100):
    array[j,a[j]] = 1
cols = ["no_crime","infraction", "misdimeanor", "felony"]
df = pd.DataFrame(array, columns=cols, dtype=np.int16)
df

no_crime  infraction  misdimeanor  felony
0          0           0            0       1
1          0           0            0       1
2          0           0            0       1
3          0           0            1       0
4          0           0            1       0
..       ...         ...          ...     ...
95         0           1            0       0
96         0           0            0       1
97         1           0            0       0
98         0           0            1       0
99         0           0            0       1

[100 rows x 4 columns]

In [140]:
df['x_3_ord'] = (df.no_crime == 0)
df['x_3_ord'] = df['x_3_ord'].astype(np.int16)
df.sort_values('x_3_ord')

no_crime  infraction  misdimeanor  felony  x_3_ord
49         1           0            0       0        0
56         1           0            0       0        0
50         1           0            0       0        0
58         1           0            0       0        0
43         1           0            0       0        0
..       ...         ...          ...     ...      ...
29         0           0            0       1        1
27         0           1            0       0        1
26         0           0            0       1        1
54         0           0            1       0        1
99         0           0            0       1        1

[100 rows x 5 columns]

24. What should the sum of each row be (in English)? 

<span style="color:pink">sum of each column should be the total number of each kind of crime, except for x_3_ord which will just tell you total number of all crimes</span></br>

25. Verify that. 

In [141]:
# TO-DO
df.sum()

no_crime       22
infraction     22
misdimeanor    25
felony         31
x_3_ord        78
dtype: int64

26. How should the column sum look (in English)? 
<span style="color:pink">We should expect for x_3_ord and no_crime to sum up to 100, and the sum of all columns exclusing x_3_ord should also be 100</span></br>


27. Verify that.

In [145]:
# TO-DO
print('sum of all columns: ',df.sum().sum() - df['x_3_ord'].sum())
print('sum of all x_3_ord and no_crime: ',df.no_crime.sum() + df['x_3_ord'].sum())

sum of all columns:  100
sum of all x_3_ord and no_crime:  100


28. Generate a Pandas DataFrame with 100 rows where:

* The first column is realization from a normal with mean 17 and variance 38.
* The second column is uniform between -10 and 10.
* The third column is poisson with mean 6.
* The fourth column in exponential with lambda of 9.
* The fifth column is binomial with n = 20 and p = 0.12.
* and the sixth column is a binary variable with exactly 24% 1's dispersed randomly.

Name the rows the entries of the `fake_first_names` list.

In [172]:
fake_first_names = ["Sophia", "Emma", "Olivia", "Ava", "Mia", "Isabella", "Riley", 
  "Aria", "Zoe", "Charlotte", "Lily", "Layla", "Amelia", "Emily", 
  "Madelyn", "Aubrey", "Adalyn", "Madison", "Chloe", "Harper", 
  "Abigail", "Aaliyah", "Avery", "Evelyn", "Kaylee", "Ella", "Ellie", 
  "Scarlett", "Arianna", "Hailey", "Nora", "Addison", "Brooklyn", 
  "Hannah", "Mila", "Leah", "Elizabeth", "Sarah", "Eliana", "Mackenzie", 
  "Peyton", "Maria", "Grace", "Adeline", "Elena", "Anna", "Victoria", 
  "Camilla", "Lillian", "Natalie", "Jackson", "Aiden", "Lucas", 
  "Liam", "Noah", "Ethan", "Mason", "Caden", "Oliver", "Elijah", 
  "Grayson", "Jacob", "Michael", "Benjamin", "Carter", "James", 
  "Jayden", "Logan", "Alexander", "Caleb", "Ryan", "Luke", "Daniel", 
  "Jack", "William", "Owen", "Gabriel", "Matthew", "Connor", "Jayce", 
  "Isaac", "Sebastian", "Henry", "Muhammad", "Cameron", "Wyatt", 
  "Dylan", "Nathan", "Nicholas", "Julian", "Eli", "Levi", "Isaiah", 
  "Landon", "David", "Christian", "Andrew", "Brayden", "John", 
  "Lincoln"]

# TO-DO
df = pd.DataFrame()
df['names'] = fake_first_names
df = df.set_index('names')
df['1'] = np.random.normal(17,38, size = df.shape[0])
df['2'] = np.random.uniform(-10,10, size = df.shape[0])
df['3'] = np.random.poisson(6, size=df.shape[0])
df['4'] = np.random.exponential(9, size=df.shape[0])
df['5'] = np.random.binomial(n=20,p=0.12,size=df.shape[0])
df['6'] = random.choices([0,1],weights=[76,24],k=df.shape[0])
df

1         2  3          4  5  6
names                                             
Sophia     40.829762 -9.756126  6  46.824084  1  0
Emma       34.833281 -2.756712  8  10.730208  2  0
Olivia      2.327557  0.202463  7   0.591315  2  0
Ava        27.281128  2.062833  7  25.651552  4  0
Mia       -53.356680 -3.084459  3   1.834804  1  0
...              ...       ... ..        ... .. ..
Christian -11.313041 -9.527140  3   6.259422  3  0
Andrew     -8.418361  1.161247  8   3.849820  0  0
Brayden    15.211233  2.705160  6   2.058810  2  0
John       58.964043  7.001681  3   9.778721  2  0
Lincoln    15.559065  1.265284  3   1.154972  1  1

[100 rows x 6 columns]

29. Create a data frame of the same data as above except make the binary variable a factor "DOMESTIC" vs "FOREIGN" for 0 and 1 respectively. Use RStudio's `View` function to ensure this worked as desired.

In [174]:
# TO-DO
df['6'] = df['6'].replace({0:"DOMESTIC",1:'FOREIGN'})
df

1         2  3          4  5         6
names                                                    
Sophia     40.829762 -9.756126  6  46.824084  1  DOMESTIC
Emma       34.833281 -2.756712  8  10.730208  2  DOMESTIC
Olivia      2.327557  0.202463  7   0.591315  2  DOMESTIC
Ava        27.281128  2.062833  7  25.651552  4  DOMESTIC
Mia       -53.356680 -3.084459  3   1.834804  1  DOMESTIC
...              ...       ... ..        ... ..       ...
Christian -11.313041 -9.527140  3   6.259422  3  DOMESTIC
Andrew     -8.418361  1.161247  8   3.849820  0  DOMESTIC
Brayden    15.211233  2.705160  6   2.058810  2  DOMESTIC
John       58.964043  7.001681  3   9.778721  2  DOMESTIC
Lincoln    15.559065  1.265284  3   1.154972  1   FOREIGN

[100 rows x 6 columns]

30. Print out a table of the binary variable. Then print out the proportions of "DOMESTIC" vs "FOREIGN".

In [177]:
# TO-DO
print(df['6'])
print("Domestic: ", (df['6'] == "DOMESTIC").sum())
print("Foreign: ", (df['6'] == "FOREIGN").sum())


names
Sophia       DOMESTIC
Emma         DOMESTIC
Olivia       DOMESTIC
Ava          DOMESTIC
Mia          DOMESTIC
               ...   
Christian    DOMESTIC
Andrew       DOMESTIC
Brayden      DOMESTIC
John         DOMESTIC
Lincoln       FOREIGN
Name: 6, Length: 100, dtype: object
Domestic:  78
Foreign:  22


31. Print out a summary of the whole dataframe.

In [180]:
# TO-DO
df.head()

1         2  3          4  5         6
names                                                 
Sophia  40.829762 -9.756126  6  46.824084  1  DOMESTIC
Emma    34.833281 -2.756712  8  10.730208  2  DOMESTIC
Olivia   2.327557  0.202463  7   0.591315  2  DOMESTIC
Ava     27.281128  2.062833  7  25.651552  4  DOMESTIC
Mia    -53.356680 -3.084459  3   1.834804  1  DOMESTIC

32. Output summary statistics of the DataFrame.

In [181]:
# To-DO
df.describe()

1           2           3           4          5
count  100.000000  100.000000  100.000000  100.000000  100.00000
mean    10.508613   -1.303457    5.930000    9.300610    2.49000
std     39.811654    5.649534    2.433997   11.188098    1.47364
min   -114.292836   -9.779669    1.000000    0.007856    0.00000
25%    -16.351247   -5.809962    4.000000    2.478581    2.00000
50%     11.157573   -2.312818    6.000000    5.914096    2.00000
75%     37.157192    2.474193    8.000000   11.221598    4.00000
max    101.422724    9.796994   12.000000   70.118348    7.00000

33. Let `n = 50`. Create a n x n matrix `A` of exactly 50% entries 0's, 25% 1's 25% 2's. These values should be in random locations.

In [194]:
# TO-DO
arr = random.choices([0,1,2],weights=[50,25,25],k=2500)
arr = np.reshape(arr,(50,50)).astype(np.float16)
arr

array([[0., 0., 2., ..., 1., 0., 0.],
       [1., 2., 2., ..., 0., 0., 0.],
       [1., 0., 2., ..., 1., 0., 0.],
       ...,
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 2., ..., 0., 0., 0.]], dtype=float16)

34. Randomly punch holes (i.e. `NAN`) values in this matrix so that an each entry is missing with probability 30%. Hint: NumPy has a `np.nan` function.

In [196]:
# TO-DO
index = random.choices([0,1],weights=[70,30],k=2500)
index = np.reshape(index,(50,50))
ind = np.where(index == 1)
arr[ind] = np.nan
arr

array([[nan, nan,  2., ..., nan,  0.,  0.],
       [nan,  2., nan, ...,  0.,  0., nan],
       [ 1.,  0.,  2., ...,  1., nan,  0.],
       ...,
       [ 1.,  0.,  1., ...,  0.,  0., nan],
       [ 0.,  1.,  0., ..., nan, nan,  0.],
       [ 0., nan,  2., ..., nan,  0., nan]], dtype=float16)

35. Sort the rows in matrix `A` by the largest row sum to lowest. Be careful about the NAN's!

<span style="color:pink">numpy nansum counts nans as 0</span>

In [200]:
# TO-DO
np.sort(np.nansum(arr,axis=1))

array([ 8.,  9., 10., 10., 11., 12., 12., 12., 12., 13., 13., 13., 14.,
       14., 14., 14., 15., 16., 16., 16., 16., 16., 17., 17., 17., 18.,
       18., 18., 18., 19., 19., 19., 19., 19., 19., 20., 20., 20., 20.,
       21., 21., 21., 22., 22., 22., 23., 24., 24., 25., 28.],
      dtype=float16)

36. Set a seed and then create a list `v` consisting of a sample of 1,000 iid normal realizations with mean -10 and variance 100.

In [204]:
# TO-DO
v = np.random.normal(-10,100,size=1000)

37. Repeat (36) with a new seed. Save this new result to `w`.

In [205]:
# TO-DO
w = np.random.normal(-10,100,size=1000)

38. Find the average of `v` and the standard error of `v`.

In [208]:
# TO-DO
print("Average v: ",np.mean(v))
print("Error: ", ((-10-np.mean(v))/-10 * 100 ),"%")

Average v:  -9.823748538621958
Error:  1.7625146137804213 %


39. Find the 5%ile of `v` using the Numpy library, read documentation to figure out which function to use. Is the estimate about what is expected by theory?

Yes, the 5th percentile is towards the edge of the bell curve and is expected to be significantly different from the average

In [209]:
# TO-DO
np.percentile(v,5)

-174.84990405856652

40. What is the percentile of `v` that corresponds to the value 0? What should it be theoretically? Is the estimate about what is expected by theory?
<span style="color:red">It is 53rd percentile, theoretically 0 should be in 50th percentile our estimate is close</span>

In [227]:
# TO-DO
np.percentile(v,52.82)

0.011838842438702118