# Lab 2 - Python Lab
## Author: *your name here*
## Date: 11:59PM February 25, 2021

#### More Basic R Skills

1. Create a function `my_reverse` which takes as required input a vector `v` and returns the vector in reverse where the first entry is the last entry, etc. No function calls are allowed inside your function otherwise that would defeat the purpose of the exercise! (Yes, there is a base R function that does this called `rev`). Use `head` on `v` and `tail` on `my_reverse(v)` to verify it works.

In [1]:
# TO-DO
import numpy as np
def reverse(v):
    return np.flip(v)

reverse([1,2,3,4,5])

array([5, 4, 3, 2, 1])

2. Create a function `flip_matrix` which takes as required input a matrix, an argument `dim_to_rev` that returns the matrix with the rows in reverse order or the columns in reverse order depending on the `dim_to_rev` argument. Let the default be the dimension of the matrix that is greater.

In [12]:
# TO-DO
def revMatrix(m, dim_to_rev="col"):
    if dim_to_rev == "row":
        for i in range(len(m)):
            m[i] = np.flip(m[i])
        return m
    if dim_to_rev == "col":
        for i in range(len(m[0,:])):
            m[:,i] = np.flip(m[:,i])
        return m
print('Original')
print(np.array([[1,2,3],[4,5,6],[7,8,9]]))
print("Test1: col")
print(revMatrix(np.array([[1,2,3],[4,5,6],[7,8,9]]),"col"))
print("Test2: row")
print(revMatrix(np.array([[1,2,3],[4,5,6],[7,8,9]]),"row"))

Original
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Test1: col
[[7 8 9]
 [4 5 6]
 [1 2 3]]
Test2: row
[[3 2 1]
 [6 5 4]
 [9 8 7]]


3. Create a list named `my_list` with keys "A", "B", ... where the entries are lists of size 1, 2 x 2, 3 x 3 x 3, etc. Fill the array with the numbers 1, 2, 3, etc. Make 8 entries according to this sequence. Be sure to import numpy.

In [ ]:
# TO-DO
my_list = 

In [ ]:
# run this code
my_list.shape

4. Use `help(np.matrix.shape)` to read about what these functions do. Then explain the output you see above. For the later arrays, does it make sense given the dimensions of the arrays?

In [ ]:
help(np.matrix.shape)

5. Try to intelligently store this data. Use the data structure you think is suitable for this data.

* M / Boomer: "Theodore, Bernard, Gene, Herbert, Ray, Tom, Lee, Alfred, Leroy, Eddie"
* M / GenX: "Marc, Jamie, Greg, Darryl, Tim, Dean, Jon, Chris, Troy, Jeff"
* M / Millennial: "Zachary, Dylan, Christian, Wesley, Seth, Austin, Gabriel, Evan, Casey, Luis"
* F / Boomer: "Gloria, Joan, Dorothy, Shirley, Betty, Dianne, Kay, Marjorie, Lorraine, Mildred"
* F / GenX: "Tracy, Dawn, Tina, Tammy, Melinda, Tamara, Tracey, Colleen, Sherri, Heidi"
* F / Millennial: "Samantha, Alexis, Brittany, Lauren, Taylor, Bethany, Latoya, Candice, Brittney, Cheyenne"

In [ ]:
# TO-DO

6. Imagine you are running an experiment with many manipulations. You have 14 levels in the variable "treatment" with levels a, b, c, etc. For each of those manipulations you have 3 submanipulations in a variable named "variation" with levels A, B, C. Then you have "gender" with levels M / F. Then you have "generation" with levels Boomer, GenX, Millenial. Then you will have 6 runs per each of these groups. In each set of 6 you will need to select a name without duplication from the appropriate set of names (from the last question). Create a data frame with columns treatment, variation, gender, generation, name and y that will store all the unique unit information in this experiment. Leave y empty because it will be measured as the experiment is executed.

In [ ]:
# TO-DO

7. Use the `my_reverse` function you created for question one and show that `my_reverse(string)` is equivalent to the reverse of the string.

In [ ]:
# TO-DO

### Multinomial Classification using KNN

8. Write a k = 1 nearest neighbor algorithm using the Euclidean distance function. The following comments are standard "Roxygen" format for documentation. Hopefully, we will get to packages at some point and we will go over this again. It is your job also to fill in this documentation.

In [ ]:
def nn_algorithm_predict(X_input, y_binary, X_test):
    """
    X_input: *describe*
    y_binary: *describe*
    X_test: *describe*
    
    return: *describe*
    """
    # TO-DO

9. Write a few tests to ensure it actually works:

In [ ]:
# TO-DO

10. We now add an argument `d` representing any legal distance function to the `nn_algorithm_predict` function. Update the implementation so it performs NN using that distance function. Set the default function to be the Euclidean distance in the original function. Also, alter the documentation in the appropriate places.

In [ ]:
# TO-DO

11. For extra credit (unless you're a masters student), add an argument `k` to the `nn_algorithm_predict` function and update the implementation so it performs KNN. In the case of a tie, choose yhat randomly. Set the default `k` to be the square root of the size of D which is an empirical rule-of-thumb popularized by the "Pattern Classification" book by Duda, Hart and Stork (2007). Also, alter the documentation in the appropriate places.

In [ ]:
# TO-DO

### Basic Binary Classification Modeling

12. Load the famous `iris` data frame into the namespace. Provide a summary of the columns using the `head`, `.summary()` and `.describe()` functions and write a few descriptive sentences about the distributions.

In [ ]:
# TO-DO

13. Describe the data.

*TO-DO*

14. The outcome / label / response is `Species`. This is what we will be trying to predict. However, we only care about binary classification between "setosa" and "versicolor" for the purposes of this exercise. Thus the first order of business is to drop one class. Let's drop the data for the level "virginica" from the data frame.

In [ ]:
# TO-DO

15. Now create a vector `y` that is length the number of remaining rows in the data frame whose entries are 0 if "setosa" and 1 if "versicolor".

In [ ]:
# TO-DO

16. Write a function `mode` returning the sample mode.

In [ ]:
# TO-DO

17. Fit a threshold model to `y` using the feature `Sepal.Length`. Write your own code to do this, preferably create a threshold function first. What is the estimated value of the threshold parameter? Save the threshold value as `threshold`. 

In [ ]:
# TO-DO

18. What is the total number of errors this model makes?

In [ ]:
# TO-DO

19. Summarize Sepal Length by the "setosa" and "versicolor" flowers. Hint: use the `groupby` Pandas function.

In [ ]:
# TO-DO

20. Does the threshold model's performance make sense given the above summaries?

*TO-DO*

21. Create the function `g` explicitly that can predict `y` from `x` being a new `Sepal.Length`.

In [ ]:
# TO-DO

## Perceptron

22. You will code the "perceptron learning algorithm" for arbitrary number of features p. Take a look at the comments above the function. Respect the spec below, and edit the documentation to your understanding of the parameters.

In [ ]:
def perceptron_learning_algorithm(X_input, y_binary, w, MAX_ITER = 1000):
    """
    X_input: *describe*
    y_binary: *describe*
    w: *describe*
    MAX_ITER: *describe*
    
    return: *describe*
    """
    # TO-DO

To understand what the algorithm is doing - linear "discrimination" between two response categories, we can draw a picture. First let's make up some very simple training data D.

In [ ]:
import pandas as pd

Xy_simple = pd.DataFrame({'response': [0, 0, 0, 1, 1, 1],
                   'first_feature': [1, 1, 2, 3, 3, 4],
                   'second_feature': [1, 2, 1, 3, 4, 3]})

Xy_simple

We haven't spoken about visualization yet, but it is important we do some of it now. Thus, I will write this code for you and you will just run it. First we load the visualization library we're going to use:

In [ ]:
# Lets plot the data using the Pandas plot() function
Xy_simple.plot(x ='first_feature',
                y='second_feature', 
                kind = 'scatter',
                c = 'response',
                cmap="viridis")

23. Run the `perceptron_learning_algorithm` and explain the output. What do the numbers mean? What is the intercept of this line and the slope? You will have to do some algebra.

*TO-DO*

24. Plot the perceptron line on the graph.

In [ ]:
# TO-DO

25. Explain this picture. Why is this line of separation "satisfying" or not to you?

*TO-DO*

26. For extra credit, program the maximum-margin hyperplane perceptron that provides the best linear discrimination model for linearly separable data. Make sure you provide ROxygen documentation for this function.

In [ ]:
# TO-DO